training:
  DEFAULT_MODEL: LOGISTIC_REGRESSION
  MODELS:
    GRADIENT_BOOSTING:
      learning_rate: 0.1
      loss: log_loss
      max_depth: 3
      n_estimators: 100
      random_state: 86
    LOGISTIC_REGRESSION:
      C: '0.8'
      max_iter: '1000'
      penalty: l2
      random_state: '86'
    RANDOM_FOREST:
      max_depth: 20
      n_estimators: 250
      random_state: 86
  TARGET_COLUMN: Survived
transform_data:
  DROPPED_COLUMNS:
  - PassengerId
  - Name
  - Ticket
  - Cabin
  RANDOM_SEED: 86
  TEST_SIZE: 0.2
validator:
  threshold: 0.1
