prueba: false
training:
  DEFAULT_MODEL: GRADIENT_BOOSTING
  MODELS:
    GRADIENT_BOOSTING:
      learning_rate: '0.08'
      loss: log_loss
      max_depth: '5'
      n_estimators: '40'
      random_state: '86'
    LOGISTIC_REGRESSION:
      C: '1.0'
      max_iter: '1000'
      penalty: l1
      random_state: '86'
      solver: saga
    RANDOM_FOREST:
      max_depth: 8
      n_estimators: 250
      random_state: 86
  TARGET_COLUMN: Survived
transform_data:
  DROPPED_COLUMNS:
  - PassengerId
  - Name
  - Ticket
  - Cabin
  RANDOM_SEED: 86
  TEST_SIZE: 0.2
validator:
  threshold: 0.1
