transform_data:
  RANDOM_SEED: 86
  TEST_SIZE: 0.2
  DROPPED_COLUMNS:
    - PassengerId
    - Name
    - Ticket
    - Cabin

training:
  TARGET_COLUMN: Survived
  
  MODELS:
    LOGISTIC_REGRESSION:
      penalty: l2
      C: 0.8
      max_iter: 100
      random_state: 86
    
    GRADIENT_BOOSTING:
      loss: log_loss
      learning_rate: 0.1
      n_estimators: 100
      max_depth: 3
      random_state: 86

    RANDOM_FOREST:
      n_estimators: 250
      max_depth: 15
      random_state: 86

validator:
  threshold: 0.1
