artifacts_dir: artifact/

data_ingestion:
  directory: artifact/data_ingestion
  source_url:
    https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/Titanic.csv
  local_data_file: artifact/data_ingestion/raw_data/Titanic.csv
  raw_data_path: artifact/data_ingestion/raw_data
  train_data_path: artifact/data_ingestion/train_data
  test_data_path: artifact/data_ingestion/test_data

data_validation:
  directory: artifact/data_validation
  status: artifact/data_validation/status.txt
  local_csv_file: artifact/data_ingestion/raw_data/Titanic.csv

data_transformation:
  directory: artifact/data_transformation
  transformation_artifacts: artifact/data_transformation/artifacts
  tranformation_info: artifact/data_transformation/transformation_info.txt
  training_csv_dir: artifact/data_ingestion/train_data/train.csv
  testing_csv_dir: artifact/data_ingestion/test_data/test.csv
  preprocessor_file_path: artifact/data_transformation/artifacts/preprocessing.pkl

model_trainer:
  directory: artifact/model_trainer

  model_path: artifact/model_trainer/model.pkl
  model_report: artifact/model_trainer/model_report.json
  model_registry: artifact/model_trainer/model_registry.json

  training_csv_dir: artifact/data_ingestion/train_data/train.csv
  testing_csv_dir: artifact/data_ingestion/test_data/test.csv

model_validator:
  directory: artifact/model_validator
  best_model_path: artifact/model_validator/best_model
  best_model_artifacts_path: artifact/model_validator/best_model/artifacts
  model_registry: artifact/model_validator/registry.txt

serving:
  serving_model: artifact/model_validator/best_model/model.pkl

explainer:
  directory: artifact/explainer
  explainer_path: artifact/explainer/explainer.pkl